### ISSUE TITLE
Error while running Alphafold without docker

### ISSUE THREAD

**Issue by skhatri007** [kalininalab/alphafold_non_docker#32] opened 2021-12-28 10:42 UTC
Hi all,
I am facing the below error while running alphafold.
File "/mnt/Alphafold/No_doc/alphafold/run_alphafold.py", line 427, in <module>
    app.run(main)
  File "/home/skhatri/anaconda3/envs/alphafold/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/skhatri/anaconda3/envs/alphafold/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/mnt/Alphafold/No_doc/alphafold/run_alphafold.py", line 403, in main
    predict_structure(
  File "/mnt/Alphafold/No_doc/alphafold/run_alphafold.py", line 166, in predict_structure
    feature_dict = data_pipeline.process(
  File "/mnt/Alphafold/No_doc/alphafold/alphafold/data/pipeline_multimer.py", line 266, in process
    chain_features = self._process_single_chain(
  File "/mnt/Alphafold/No_doc/alphafold/alphafold/data/pipeline_multimer.py", line 212, in _process_single_chain
    chain_features = self._monomer_data_pipeline.process(
  File "/mnt/Alphafold/No_doc/alphafold/alphafold/data/pipeline.py", line 170, in process
    msa_for_templates = parsers.deduplicate_stockholm_msa(
  File "/mnt/Alphafold/No_doc/alphafold/alphafold/data/parsers.py", line 350, in deduplicate_stockholm_msa
    query_align = next(iter(sequence_dict.values()))
**StopIteration**
I don't understand where the issue is, as it runs fine with other sequences in alphafold multimer . I use the default input method for multimer .
Please help!

**Comment by Old-Shatterhand** [comment] 2023-02-21 10:28
Hi @skatri,

could you provide us with the input? Then, we can reproduce the issue. Anyways, it seems to be an issue in the AlphaFold-code.

Best, Roman

**Comment by Old-Shatterhand** [comment] 2024-04-12 14:47
I'll close it for now, if it's still a problem, we can reopen it at at a later point.

**Closed by Old-Shatterhand** 2024-04-12 14:47 UTC

**Comment by Comp-era** [comment] 2024-04-13 03:32
Hi ,
Sorry for late reply. The problem has been solved. Thanks for your help.

Regards
*Shantanu Khatri,*
*PhD Scholar (CSIR-SRF)*
*C/o- Dr.Lipi Thukral*
*Senior Scientist*

*Computational and Structural Biology Group(CSB)*
*CSIR-IGIB, Mathura road*
*New Delhi-110025*
